[package]
name = "module-walk"
version = "0.1.0"
authors = ["Shiranka Miskin <smiskin@slack-corp.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
